name: Release Statically Linked Rust Library

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu       # Linux (x86_64)
          - aarch64-unknown-linux-gnu      # Linux (aarch64)

    env:
      LIBRARY_NAME: project  # Change this to match your library name in Cargo.toml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Target for Cross Compilation
        run: rustup target add ${{ matrix.target }}

      - name: Install Dependencies (Linux Only)
        if: contains(matrix.target, 'linux')
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu

      - name: Clean Build Artifacts
        run: cargo clean

      - name: Build with Cargo
        run: cargo build --target ${{ matrix.target }} --release --verbose

      - name: Debug Build Output
        run: ls -R target/${{ matrix.target }}/release || echo "Build output not found!"

      - name: Create Release Archive
        run: |
          mkdir -p release
          if [[ -f target/${{ matrix.target }}/release/lib$LIBRARY_NAME.so ]]; then
            cp target/${{ matrix.target }}/release/lib$LIBRARY_NAME.so release/
          elif [[ -f target/${{ matrix.target }}/release/lib$LIBRARY_NAME.dylib ]]; then
            cp target/${{ matrix.target }}/release/lib$LIBRARY_NAME.dylib release/
          elif [[ -f target/${{ matrix.target }}/release/$LIBRARY_NAME.dll ]]; then
            cp target/${{ matrix.target }}/release/$LIBRARY_NAME.dll release/
          else
            echo "ERROR: Library file not found!"
            exit 1
          fi
          tar -czvf ${{ matrix.target }}.tar.gz -C release .

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
        env:
          EGOR: ${{ secrets.EGOR }}
