name: Release Multiplatform Rust Binary

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like 'v1.0.0'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    runs-on: ${{ matrix.os }}

    env:
      BINARY_NAME: Project

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: cargo install cross --force

      - name: Install Target for Cross Compilation
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cargo build --target ${{ matrix.target }} --release
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cargo build --target ${{ matrix.target }} --release
          else
            cross build --target ${{ matrix.target }} --release --verbose

      - name: Create Release Archive
        run: |
          mkdir -p release

          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            cp target/${{ matrix.target }}/release/$BINARY_NAME.exe release/
            zip -r release/${{ matrix.target }}.zip release/$BINARY_NAME.exe
          elif [[ "${{ matrix.target }}" == *"darwin"* ]]; then
            cp target/${{ matrix.target }}/release/$BINARY_NAME release/
            tar -czvf release/${{ matrix.target }}.tar.gz -C release $BINARY_NAME
          else
            cp target/${{ matrix.target }}/release/$BINARY_NAME release/
            tar -czvf release/${{ matrix.target }}.tar.gz -C release $BINARY_NAME
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT }}
