name: Release Statically Linked Rust Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-musl
          - os: ubuntu-22.04
            target: aarch64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    env:
      BINARY_NAME: Project

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        if: runner.os == 'Linux'
        run: |
          if [[ "${{ matrix.target }}" == *"windows-gnu"* ]]; then
            sudo apt-get update
            sudo apt-get install -y mingw-w64
          fi

      - name: Install Target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: |
          cargo build --target ${{ matrix.target }} --release

      - name: Create Release Archive
        run: |
          mkdir -p release
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            cp target/${{ matrix.target }}/release/$BINARY_NAME.exe release/
            zip -r release/${{ matrix.target }}.zip release/$BINARY_NAME.exe
          else
            cp target/${{ matrix.target }}/release/$BINARY_NAME release/
            tar -czvf release/${{ matrix.target }}.tar.gz -C release $BINARY_NAME
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.tar.gz
            release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.Project }}
